version: '4.28'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: base
    container_name: api
    env_file:
      - ./.env
    image: api
    ports:
      - '${PORT}:${PORT}'